// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolDBCoreWebAPI.Models;

#nullable disable

namespace SchoolDBCoreWebAPI.Migrations
{
    [DbContext(typeof(SchoolDBContext))]
    partial class SchoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolDBCodeFirstApp.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId")
                        .HasName("PK__Grade");

                    b.ToTable("grades", "School");
                });

            modelBuilder.Entity("SchoolDBCodeFirstApp.Models.Student", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Studentid"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Studentid")
                        .HasName("PK__Student");

                    b.HasIndex("GradeId");

                    b.ToTable("students", "School");
                });

            modelBuilder.Entity("SchoolDBCodeFirstApp.Models.User", b =>
                {
                    b.Property<int>("UsertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsertId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsertId")
                        .HasName("PK__User");

                    b.ToTable("users", "School");

                    b.HasData(
                        new
                        {
                            UsertId = 1,
                            Email = "pranaya.rout@teksystems.com",
                            FullName = "Pranaya Rout",
                            PassWordHash = "ayRIdQoJLhXyufbY11KD1fXqmpf4aHDEXLWsdYmLZek=",
                            Role = "Adminstrator,Manager"
                        },
                        new
                        {
                            UsertId = 2,
                            Email = "john.doe@teksystems.com",
                            FullName = "John Doe",
                            PassWordHash = "ZlKyJQ6uc/cQ0FZNsH/AqjoLvXeATZrliDoFdEMm6pk=",
                            Role = "Administrator"
                        },
                        new
                        {
                            UsertId = 3,
                            Email = "jane.smith@teksystems.com",
                            FullName = "Jane Smith",
                            PassWordHash = "sKmBLz4SePwSKvTys+H4Zs9IpVJ7uaVmTJfqWPV5OzE=",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("SchoolDBCodeFirstApp.Models.Student", b =>
                {
                    b.HasOne("SchoolDBCodeFirstApp.Models.Grade", "grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__grades__students");

                    b.Navigation("grade");
                });

            modelBuilder.Entity("SchoolDBCodeFirstApp.Models.Grade", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
